### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by aspark21** [ecampbell/moodle-qformat_wordtable#6]
Updating from wordtable 0aa164807668a5a3e2ed956a519027cfc2d358b1
to 5b32ac5928de3f451a6b063e7c3c0b3ccd1f1113 results in the following warning during upgrade:

![Screenshot 2020-07-13 at 10 03 34](https://user-images.githubusercontent.com/4015496/87308910-d5308a00-c513-11ea-8ca3-ddad8be06ad7.png)

Seems to complete none the less

**Comment by aspark21** [comment]
Looking at https://github.com/ecampbell/moodle-qformat_wordtable/blob/master/db/upgrade.php#L35 
It seems like this only comes up because we do have debugging set to verbose and this isn't a significant issue since upgrade.php and install.php remain unchanged

**Comment by ecampbell** [comment]
Thanks for this, I had forgotten about them. They'll be gone in the next release.
