### ISSUE TITLE
Error importing and exporting issues

### ISSUE THREAD

**Issue by jmfreire1980** [ecampbell/moodle-qformat_wordtable#7]
Eloin can you help me with the following error that occurs when importing and exporting issues:
Exceção - Call to undefined function get_contributed_question_labels()

**Comment by ecampbell** [comment]
Can you tell me what version of Moodle, and what version of the plugin you are using please?

**Comment by jmfreire1980** [comment]
Helo!

I am using version 3.10.1+ (Build: 20210122) and the version of the Microsoft Word File Import / Export (Question Format) plugin is Release 4.0.0 (Build: 2021041200).

Thank you very much for your reply!

**Comment by ecampbell** [comment]
Hi there, unfortunately you will have to revert to the last release of the plugin (v3.6.3), as the new release is broken. I have removed it for the moment.

**Comment by jmfreire1980** [comment]
Hello Eloin!

Thank you very much!

I will downgrade your plugin.

I would like to thank you, your plugin is very useful and very good.

Thanks!

**Comment by jmfreire1980** [comment]
Hello Eloin!

Thank you very much!

I will downgrade your plugin.

I would like to thank you, your plugin is very useful and very good.

Thanks!

**Comment by jmfreire1980** [comment]
I downgraded it and started working again!

Thanks!

**Comment by ecampbell** [comment]
4.0.0 was a dog
