### ISSUE TITLE
There are no questions in the import file.

### ISSUE THREAD

**Issue by BT0ro** [ecampbell/moodle-qformat_wordtable#8]
Hello!

When I export a question of any type (multichoice for example) and import it back to the system, I get this issue: There are no questions in the import file.
I add moodleLanguage in file properties then saved it in .docx format in LibreOffice.

The last version I tried is 3.7.0 (Build: 2020112001) with moodle 3.9.5. I Also tried 3.6.3 and 3.6.

Full debug info:
```
There are no questions in the import file

Import error

More information about this error
Debug info:
Error code: cannotimport
Stack trace:

   line 498 of /lib/setuplib.php: moodle_exception thrown
   line 122 of /question/import.php: call to print_error()
```
Also I pin file with exported question.
[question.docx](https://github.com/ecampbell/moodle-qformat_wordtable/files/6342144/question.docx)

**Comment by ecampbell** [comment]
You must open exported files using Microsoft Word. Other word-processing apps don't work. When creating questions for import, they might work better.
